### ISSUE TITLE
cannot install -- installation dependencies issues?

### ISSUE THREAD

**Issue by cboettig** [richfitz/rrlite#5]
I have `libhiredis-dev` installed but still get:

```
* installing *source* package ‘rrlite’ ...
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -Irlite/src     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c rrlite.c -o rrlite.o
In file included from rrlite.c:1:0:
rrlite.h:3:21: fatal error: hirlite.h: No such file or directory
 #include <hirlite.h>
                     ^
compilation terminated.
/usr/lib/R/etc/Makeconf:134: recipe for target 'rrlite.o' failed
make: *** [rrlite.o] Error 1
ERROR: compilation failed for package ‘rrlite’
```

Perhaps the Make/configure stuff is failing to locate the headers?   (Also, maybe these libraries should be indicated in the `SystemDependencies` in the description?)

**Comment by sckott** [comment]
@richfitz mentions that the normal `devtools::install_github` doesn't work https://github.com/ropensci/rrlite#installation  - Did you try `devtools::install_git("https://github.com/ropensci/rrlite", args="--recursive")`

**Comment by cboettig** [comment]
hm, no go for me.  It's actually `drat.builder` that is giving me this error, which doesn't use `devtools` anyhow  (though I get the same error with `devtools` version).  Any idea if that `hirlite.h` header file is supposed to be in that submodule?

**Comment by richfitz** [comment]
Yeah, the `hirlite.h` header is in the submodule.  However, upstream rlite development has slowed so perhaps I can move it from being a submodule to including the actual files?

**Comment by richfitz** [comment]
Also, rrlite does not depend on `libhiredis` (so that should not be in `SystemDependencies`), and if cloned recursively includes the source for `libhirlite` so that's also not needed by the system.

**Comment by cboettig** [comment]
okay, this sounds promising.  So what do I need to do to get either `devtools::install_git("https://github.com/ropensci/rrlite", args="--recursive")` or `drat.builder` to install this successfully?

**Comment by richfitz** [comment]
```
Error: Command failed (1)
In addition: Warning message:
`args` is deprecated 
```

I see devtools has changed again.  I don't think `--recursive` is being passed through to git correctly there.  If devtools is using git2r behind the scenes then it might not support recursive clones, because I'm not seeing a recursive clone happening :cry:

**Comment by richfitz** [comment]
Should just install directly now.  Not particularly impressed that --recursive stopped working though.

**Comment by cboettig** [comment]
yup. and `drat.builder` is happy with `rrlite` now too. thanks!
